<?php

/**
 * @file
 *  Link general CAS user functionalities to services module.
 */

/**
 * Implementation of hook_perm().
 */
function cas_user_service_perm() {
  return array(
    'get any CAS user data',
    'update any CAS user name', 
    'delete any CAS user name', 
  );
}


/**
 * Implementation of hook_service().
 */
function cas_user_service_service() {
  return array(

    // cas_user.get
    array(
      '#method'           => 'cas_user.get',
      '#callback'         => 'cas_user_service_get',
      '#access callback'  => 'cas_user_service_get_access',
      '#file'             => array('file' => 'inc', 'module' => 'cas_user_service'),
      '#args'             => array(
        array(
          '#name'           => 'uid',
          '#type'           => 'int',
          '#description'    => t('User ID.'),
        ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Get CAS username.')
    ),


    // cas_user.save
    array(
      '#method'           => 'cas_user.save',
      '#callback'         => 'cas_user_service_save',
      '#access callback'  => 'cas_user_service_save_access',
      '#file'             => array('file' => 'inc', 'module' => 'cas_user_service'),
      '#args'             => array(
        array(
          '#name'           => 'uid',
          '#type'           => 'int',
          '#description'    => t('User ID.'),
        ),
        array(
          '#name'           => 'cas_name',
          '#type'           => 'string',
          '#description'    => t('CAS username.'),
        ),
      ),
      '#return'           => 'int',
      '#help'             => t('Save CAS username.')
    ),


    // cas_user.delete
    array(
      '#method'           => 'cas_user.delete',
      '#callback'         => 'cas_user_service_delete',
      '#access callback'  => 'cas_user_service_delete_access',
      '#file'             => array('file' => 'inc', 'module' => 'cas_user_service'),
      '#args'             => array(
        array(
          '#name'           => 'uid',
          '#type'           => 'int',
          '#description'    => t('User ID.'),
        ),
      ),
      '#return'           => 'struct',
      '#help'             => t('Delete CAS username.')
    ),

  );
}